### ISSUE TITLE
Patch failes for firmware 3.5.7_002008

### ISSUE THREAD

**Issue by trilader** [JohnRev/rrlogd-patcher#4]
Patching rrlogd of firmware version `3.5.7_002008` fails.
None of the patterns match (at least the script produces no output apart from `Patch has failed`).

Model (as reported by Valetudo): `roborock.vacuum.s5`
It's a 2nd generation S50 vacuum bot.

**Comment by JohnRev** [comment]
I have not tested fw `3.5.7_002008` because it is not rootable https://github.com/dgiese/dustcloud/wiki/Xiaomi-Vacuum-Firmware

The `rrlogd` file has changed a lot so the original patch does not work

Can you test the attached [rrlogd.zip](https://github.com/JohnRev/rrlogd-patcher/files/4496313/rrlogd.zip)?
This is for version `3.5.7_002008` and should disable encryption but I can not test it because I do not want to update my vacuum.


[rrlogd.zip](https://github.com/JohnRev/rrlogd-patcher/files/4496313/rrlogd.zip)
